/**
 * Agent lifecycle: prepare session via deerbox CLI → launch in tmux → poll.
 *
 * Invokes `deerbox prepare` as a subprocess to set up the sandboxed command,
 * then wraps it in a tmux session for deer's TUI.
 */

import { join } from "node:path";
import { deerboxPrepare, deerboxDestroy } from "./deerbox";
import type { DeerConfig, PrepareResult } from "./types";
import { launchSandbox, captureTmuxPane } from "./sandbox/index";
import type { SandboxSession } from "./sandbox/index";
import { dataDir, taskWorktreePath } from "./task";
import { BYPASS_DIALOG_MAX_POLLS, BYPASS_DIALOG_POLL_MS, BYPASS_DIALOG_KEY_DELAY_MS } from "./constants";

// ── Types ────────────────────────────────────────────────────────────

export interface AgentHandle {
  taskId: string;
  sessionName: string;
  worktreePath: string;
  branch: string;
  /** Kill the tmux session. Does NOT remove the worktree. */
  kill: () => Promise<void>;
  /** Kill the tmux session AND remove the worktree, branch, auth proxy. */
  destroy: () => Promise<void>;
}

export interface ContinueSession {
  /** Task ID of the existing session to resume */
  taskId: string;
  /** Path to the existing worktree */
  worktreePath: string;
  /** Branch of the existing worktree */
  branch: string;
}

export interface AgentRunOptions {
  /** Path to the repository root */
  repoPath: string;
  /** The user's prompt / task description. If omitted, Claude runs interactively. */
  prompt?: string;
  /** Branch to base the worktree on */
  baseBranch: string;
  /** Loaded deer config (for network allowlist, env, etc.) */
  config: DeerConfig;
  /**
   * Override the model.
   * @default "sonnet"
   */
  model?: string;
  /** Callback for status updates */
  onStatus?: (status: AgentStatus) => void;
  /**
   * Pre-generated task ID. If not provided, one is generated by deerbox.
   * Pass this when you need to know the taskId before `startAgent` resolves.
   */
  taskId?: string;
  /**
   * If provided, resume an existing Claude conversation instead of starting
   * a fresh one. The worktree and branch are reused; `--continue` is passed
   * to Claude instead of the prompt.
   */
  continueSession?: ContinueSession;
  /** Callback for auth proxy log messages (shown in the TUI log panel) */
  onProxyLog?: (message: string) => void;
}

export type AgentStatus =
  | { phase: "setup"; message: string }
  | { phase: "running"; sessionName: string }
  | { phase: "failed"; error: string }
  | { phase: "cancelled" };

// ── Helpers ──────────────────────────────────────────────────────────

/**
 * Poll the tmux pane for the bypass permissions confirmation dialog
 * and dismiss it by selecting "Yes, I accept".
 */
async function dismissBypassDialog(sessionName: string): Promise<void> {
  for (let i = 0; i < BYPASS_DIALOG_MAX_POLLS; i++) {
    await Bun.sleep(BYPASS_DIALOG_POLL_MS);
    const pane = await captureTmuxPane(sessionName);
    if (!pane) return;
    const text = pane.join("\n");
    if (text.includes("Yes, I accept")) {
      // Send Down and Enter separately with a delay to avoid the race
      // where Enter confirms option 1 before Down moves to option 2.
      await Bun.spawn(["tmux", "send-keys", "-t", sessionName, "Down"], {
        stdout: "pipe", stderr: "pipe",
      }).exited;
      await Bun.sleep(BYPASS_DIALOG_KEY_DELAY_MS);
      await Bun.spawn(["tmux", "send-keys", "-t", sessionName, "Enter"], {
        stdout: "pipe", stderr: "pipe",
      }).exited;
      return;
    }
    // Claude started without the dialog
    if (text.includes("$") || text.includes("❯") || text.includes("Claude")) {
      if (!text.includes("Bypass Permissions")) return;
    }
  }
}

// ── Agent Lifecycle ──────────────────────────────────────────────────

/**
 * Start an agent: invoke deerbox prepare, launch command in tmux.
 */
export async function startAgent(options: AgentRunOptions): Promise<AgentHandle> {
  const {
    repoPath,
    prompt,
    baseBranch,
    model,
    onStatus,
    continueSession,
  } = options;

  const taskId = options.taskId ?? continueSession?.taskId;

  onStatus?.({ phase: "setup", message: "Setup: preparing sandbox..." });

  let result: PrepareResult;
  try {
    result = await deerboxPrepare({
      repoPath,
      prompt,
      baseBranch,
      config: options.config,
      model,
      taskId,
      continueSession,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    onStatus?.({ phase: "failed", error: message });
    throw err;
  }

  const sessionName = `deer-${result.taskId}`;

  onStatus?.({ phase: "setup", message: "Starting sandbox..." });

  let sandbox: SandboxSession;
  try {
    sandbox = await launchSandbox({
      sessionName,
      worktreePath: result.worktreePath,
      command: result.command,
    });
  } catch (err) {
    // Kill the daemonized auth proxy on failure
    if (result.authProxyPid) {
      try { process.kill(result.authProxyPid, "SIGTERM"); } catch { /* already dead */ }
    }
    throw err;
  }

  await dismissBypassDialog(sessionName);

  onStatus?.({ phase: "running", sessionName });

  return {
    taskId: result.taskId,
    sessionName,
    worktreePath: result.worktreePath,
    branch: result.branch,
    async kill() {
      await sandbox.stop();
      if (result.authProxyPid) {
        try { process.kill(result.authProxyPid, "SIGTERM"); } catch { /* already dead */ }
      }
    },
    async destroy() {
      await sandbox.stop();
      await deerboxDestroy(result.taskId, repoPath);
    },
  };
}

/**
 * Get the last N lines of tmux output for an agent.
 */
export async function getAgentOutput(
  sessionName: string,
  fullScrollback = false,
): Promise<string[]> {
  const lines = await captureTmuxPane(sessionName, fullScrollback);
  return lines ?? [];
}

/**
 * Full cleanup: kill sandbox, remove worktree and branch.
 */
export async function destroyAgent(handle: AgentHandle): Promise<void> {
  await handle.destroy().catch(() => {});
}

/**
 * Delete a task and clean up all associated resources: tmux session,
 * auth proxy, git worktree, branch, and task directory on disk.
 *
 * Works regardless of whether a live handle is available, so it correctly
 * cleans up historical/interrupted tasks that have no active sandbox.
 */
export async function deleteTask(
  taskId: string,
  repoPath: string,
): Promise<void> {
  // Kill the tmux session
  await Bun.spawn(
    ["tmux", "kill-session", "-t", `deer-${taskId}`],
    { stdout: "pipe", stderr: "pipe" },
  ).exited;

  await deerboxDestroy(taskId, repoPath);
}
