import type { AgentState } from "./agent-state";

export const MOCK_AGENTS: AgentState[] = [
  {
    taskId: "deer_demo0001",
    prompt: "Implement dark mode toggle for the settings page",
    baseBranch: "main",
    status: "running",
    elapsed: 247,
    lastActivity: "Writing CSS variables for dark theme tokens",
    logs: [
      { text: "Reading src/styles/theme.css", verbose: false },
      { text: "Identified 43 color tokens to update", verbose: false },
      { text: "Writing CSS variables for dark theme tokens", verbose: false },
    ],
    result: null,
    error: "",
    prState: null,
    historical: false,
    idle: false,
    creatingPr: false,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 247_000).toISOString(),
    worktreePath: "/home/user/.local/share/deer/tasks/deer_demo0001/worktree",
    branch: "deer/deer_demo0001",
    cost: null,
  },
  {
    taskId: "deer_demo0002",
    prompt: "Add CSV export to all data tables in the admin dashboard",
    baseBranch: "main",
    status: "running",
    elapsed: 583,
    lastActivity: "All done! I've added CSV export buttons to UsersTable, OrdersTable, and ProductsTable.",
    logs: [
      { text: "Added exportToCsv() utility in src/lib/export.ts", verbose: false },
      { text: "Updated 3 table components with export button", verbose: false },
      { text: "All done! I've added CSV export buttons to UsersTable, OrdersTable, and ProductsTable.", verbose: false },
    ],
    result: null,
    error: "",
    prState: null,
    historical: false,
    idle: true,
    creatingPr: false,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 583_000).toISOString(),
    worktreePath: "/home/user/.local/share/deer/tasks/deer_demo0002/worktree",
    branch: "deer/deer_demo0002",
    cost: null,
  },
  {
    taskId: "deer_demo0003",
    prompt: "Refactor user profile components to use the new design system",
    baseBranch: "main",
    status: "running",
    elapsed: 1204,
    lastActivity: "Pushing branch and opening pull request",
    logs: [
      { text: "Replaced 12 custom components with design system equivalents", verbose: false },
      { text: "Pushing branch and opening pull request", verbose: false },
    ],
    result: null,
    error: "",
    prState: null,
    historical: false,
    idle: false,
    creatingPr: true,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 1_204_000).toISOString(),
    worktreePath: "/home/user/.local/share/deer/tasks/deer_demo0003/worktree",
    branch: "deer/deer_demo0003",
    cost: null,
  },
  {
    taskId: "deer_demo0004",
    prompt: "Add unit tests for the payment processing module",
    baseBranch: "main",
    status: "running",
    elapsed: 892,
    lastActivity: "Tests passing — 94% coverage on payment module",
    logs: [
      { text: "Added 18 tests across 4 test files", verbose: false },
      { text: "Tests passing — 94% coverage on payment module", verbose: false },
    ],
    result: {
      finalBranch: "deer/deer_demo0004",
      prUrl: "https://github.com/acme/app/pull/142",
    },
    error: "",
    prState: "merged",
    historical: true,
    idle: false,
    creatingPr: false,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 892_000).toISOString(),
    worktreePath: "/home/user/.local/share/deer/tasks/deer_demo0004/worktree",
    branch: "deer/deer_demo0004",
    cost: null,
  },
  {
    taskId: "deer_demo0005",
    prompt: "Fix the N+1 query bug in the product listing endpoint",
    baseBranch: "main",
    status: "running",
    elapsed: 318,
    lastActivity: "Fixed by adding select_related() and prefetch_related() calls",
    logs: [
      { text: "Identified 3 endpoints with N+1 queries using django-debug-toolbar", verbose: false },
      { text: "Fixed by adding select_related() and prefetch_related() calls", verbose: false },
    ],
    result: {
      finalBranch: "deer/deer_demo0005",
      prUrl: "https://github.com/acme/app/pull/147",
    },
    error: "",
    prState: "open",
    historical: true,
    idle: false,
    creatingPr: false,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 318_000).toISOString(),
    worktreePath: "/home/user/.local/share/deer/tasks/deer_demo0005/worktree",
    branch: "deer/deer_demo0005",
    cost: null,
  },
  {
    taskId: "deer_demo0006",
    prompt: "Migrate the sessions table from MySQL to PostgreSQL",
    baseBranch: "main",
    status: "failed",
    elapsed: 741,
    lastActivity: "Migration script failed: column 'user_metadata' has unsupported JSON subtype",
    logs: [
      { text: "Running Alembic migration on staging database", verbose: false },
      { text: "Migration script failed: column 'user_metadata' has unsupported JSON subtype", verbose: false },
    ],
    result: null,
    error: "Migration script failed: column 'user_metadata' has unsupported JSON subtype",
    prState: null,
    historical: true,
    idle: false,
    creatingPr: false,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 741_000).toISOString(),
    worktreePath: "/home/user/.local/share/deer/tasks/deer_demo0006/worktree",
    branch: "deer/deer_demo0006",
    cost: null,
  },
  {
    taskId: "deer_demo0007",
    prompt: "Update API documentation for the v2 authentication endpoints",
    baseBranch: "main",
    status: "cancelled",
    elapsed: 95,
    lastActivity: "Cancelled by user",
    logs: [
      { text: "Reading existing OpenAPI spec", verbose: false },
    ],
    result: null,
    error: "",
    prState: null,
    historical: true,
    idle: false,
    creatingPr: false,
    updatingPr: false,
    deleted: false,
    createdAt: new Date(Date.now() - 95_000).toISOString(),
    worktreePath: "",
    branch: "deer/deer_demo0007",
    cost: null,
  },
];
